# Artificial Neural Networks

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

df = pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

We want to build a neural network that predict if a bank customer will either remain in the bank or just leave according to certain features. 

In [2]:
X = df.iloc[:,3:13].values
y = df.iloc[:,13].values

#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_geography = LabelEncoder()
labelencoder_X_gender = LabelEncoder()
X[:,1] = labelencoder_X_geography.fit_transform(X[:,1])
X[:,2] = labelencoder_X_gender.fit_transform(X[:,2])

#onehotencoder_X_geography = OneHotEncoder(categorical_features=[1])
#X = onehotencoder_X_geography.fit_transform(X).toarray()
transformer = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1])], remainder='passthrough')
X = transformer.fit_transform(X.tolist())

X = X[:,1:] #avoiding the dummy trap

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

C:\Users\Charl\Mes logiciels\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Charl\Mes logiciels\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Charl\Mes logiciels\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by Stand

## Build our ANN

In [3]:
import keras 
from keras.models import Sequential
from keras.layers import Dense

#initialize the ANN
neural_network = Sequential()
#Add the input layer and the first hidden layer (with relu activation function)
neural_network.add(Dense(input_dim = 11, units = 6, kernel_initializer = 'uniform', activation = 'relu'))
#Add the second hidden layer
neural_network.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
#Add the output layer 
neural_network.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#Compile the ANN
#We use the ADAM gradient descent optimization algorithm and the binary cross entropy as loss function (which is the same as the logistic regression loss function)
neural_network.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

neural_network.fit(X_train, y_train, batch_size = 64, epochs = 100)

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
7500/7500 [==============================] - 1s 182us/step - loss: 0.6543 - acc: 0.7940
Epoch 2/100
7500/7500 [==============================] - 0s 38us/step - loss: 0.4833 - acc: 0.7963
Epoch 3/100
7500/7500 [==============================] - 0s 38us/step - loss: 0.4393 - acc: 0.7963
Epoch 4/100
7500/7500 [==============================] - 0s 40us/step - loss: 0.4345 - acc: 0.7963
Epoch 5/100
7500/7500 [==============================] - 0s 33us/step - loss: 0.4323 - acc: 0.7963
Epoch 6/100
7500/7500 [==============================] - 0s 42us/step - loss: 0.4309 - acc: 0.7963
Epoch 7/100
7500/7500 [==============================] - 0s 32us/step - loss: 0.4298 - acc: 0.7963
Epoch 8/100
7500/7500 [==============================] - 0s 36us/step - loss: 0.4288 - acc: 0.7963
Epoch 9/100
7500/7500 [==============================] - 0s 40us/step - loss: 0.4277 - 

7500/7500 [==============================] - 0s 30us/step - loss: 0.4011 - acc: 0.8344
Epoch 77/100
7500/7500 [==============================] - 0s 37us/step - loss: 0.4011 - acc: 0.8357
Epoch 78/100
7500/7500 [==============================] - 0s 39us/step - loss: 0.4011 - acc: 0.8349
Epoch 79/100
7500/7500 [==============================] - 0s 34us/step - loss: 0.4013 - acc: 0.8343
Epoch 80/100
7500/7500 [==============================] - 0s 38us/step - loss: 0.4012 - acc: 0.8344
Epoch 81/100
7500/7500 [==============================] - 0s 41us/step - loss: 0.4010 - acc: 0.8349
Epoch 82/100
7500/7500 [==============================] - 0s 32us/step - loss: 0.4008 - acc: 0.8340
Epoch 83/100
7500/7500 [==============================] - 0s 34us/step - loss: 0.4008 - acc: 0.8361
Epoch 84/100
7500/7500 [==============================] - 0s 36us/step - loss: 0.4010 - acc: 0.8355
Epoch 85/100
7500/7500 [==============================] - 0s 34us/step - loss: 0.4008 - acc: 0.8353
Epoch 86/100


## Evaluate our ANN

In [4]:
y_pred = neural_network.predict(X_test)
y_pred = (y_pred > 0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy : ',(cm[0][0]+cm[1][1])/y_test.shape[0])

[[1925   66]
 [ 322  187]]
Accuracy :  0.8448


## Predict a new observation

We want to know if the customer with the following informations will leave the bank : 

Geography: France  
Credit Score: 800  
Gender: Female  
Age: 35  
Tenure: 5  
Balance: 70000  
Number of Products: 1
Has Credit Card: Yes  
Is Active Member: Yes  
Estimated Salary: 50000

In [5]:
X_new = sc_X.transform(np.array([[0.0, 0, 800, 0, 35, 5, 70000, 1, 1, 1, 50000]]))
a = neural_network.predict(X_new)
print(a)
new_pred = (a > 0.5) 
new_pred

[[0.10461256]]


array([[False]])

To conclude, this customer won't leave the bank.  
## Better evaluate our ANN

In [6]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

def build_neural_network():
    neural_network = Sequential()
    neural_network.add(Dense(input_dim = 11, units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    neural_network.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    neural_network.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    neural_network.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return neural_network

neural_network = KerasClassifier(build_fn = build_neural_network, batch_size = 64, epochs = 100)
#n_jobs = -1 means all CPU are doing the computation
accuracies = cross_val_score(estimator = neural_network, X = X_train, y = y_train, cv = 10, n_jobs = -1)
print('Accuracies : ', accuracies)
print('Mean accuracy : ', accuracies.mean())
print('Standard deviation accuracy : ', accuracies.std())

Accuracies :  [0.83466667 0.844      0.836      0.836      0.84666667 0.832
 0.82       0.82666667 0.816      0.852     ]
Mean accuracy :  0.8344000001271565
Standard deviation accuracy :  0.010812338608435878


## Improve our ANN  
We are going to use dropout technic in order to prevent our neural network to overfit.

In [11]:
from keras.layers import Dropout

neural_network = Sequential()
neural_network.add(Dense(input_dim = 11, units = 6, kernel_initializer = 'uniform', activation = 'relu'))
neural_network.add(Dropout(rate = 0.1)) #20% chance for each unit of this layer to be desactivated for each iteration
neural_network.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu')) 
neural_network.add(Dropout(rate = 0.1))
neural_network.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
neural_network.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

neural_network.fit(X_train, y_train, batch_size = 64, epochs = 100)

Epoch 1/100
7500/7500 [==============================] - 2s 228us/step - loss: 0.6627 - acc: 0.7913
Epoch 2/100
7500/7500 [==============================] - 0s 43us/step - loss: 0.5100 - acc: 0.7963
Epoch 3/100
7500/7500 [==============================] - 0s 46us/step - loss: 0.4463 - acc: 0.7963
Epoch 4/100
7500/7500 [==============================] - 0s 44us/step - loss: 0.4415 - acc: 0.7963
Epoch 5/100
7500/7500 [==============================] - 0s 45us/step - loss: 0.4380 - acc: 0.7963
Epoch 6/100
7500/7500 [==============================] - 0s 46us/step - loss: 0.4370 - acc: 0.7963
Epoch 7/100
7500/7500 [==============================] - 0s 39us/step - loss: 0.4348 - acc: 0.7963
Epoch 8/100
7500/7500 [==============================] - 0s 45us/step - loss: 0.4323 - acc: 0.7963
Epoch 9/100
7500/7500 [==============================] - 0s 43us/step - loss: 0.4342 - acc: 0.7963
Epoch 10/100
7500/7500 [==============================] - 0s 44us/step - loss: 0.4312 - acc: 0.7963
Epoch 11

7500/7500 [==============================] - 0s 37us/step - loss: 0.4193 - acc: 0.8291
Epoch 84/100
7500/7500 [==============================] - 0s 45us/step - loss: 0.4233 - acc: 0.8261
Epoch 85/100
7500/7500 [==============================] - 0s 41us/step - loss: 0.4215 - acc: 0.8265
Epoch 86/100
7500/7500 [==============================] - 0s 41us/step - loss: 0.4228 - acc: 0.8297
Epoch 87/100
7500/7500 [==============================] - 0s 43us/step - loss: 0.4213 - acc: 0.8276
Epoch 88/100
7500/7500 [==============================] - 0s 40us/step - loss: 0.4201 - acc: 0.8303
Epoch 89/100
7500/7500 [==============================] - 0s 45us/step - loss: 0.4219 - acc: 0.8293
Epoch 90/100
7500/7500 [==============================] - 0s 38us/step - loss: 0.4243 - acc: 0.8308
Epoch 91/100
7500/7500 [==============================] - 0s 42us/step - loss: 0.4245 - acc: 0.8268
Epoch 92/100
7500/7500 [==============================] - 0s 43us/step - loss: 0.4204 - acc: 0.8301
Epoch 93/100


In [12]:
y_pred = neural_network.predict(X_test)
y_pred = (y_pred > 0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy : ',(cm[0][0]+cm[1][1])/y_test.shape[0])

[[1942   49]
 [ 350  159]]
Accuracy :  0.8404


## Tune our ANN  
This gridsearch hyperparameters tuning will take very long time to run.

In [ ]:
from sklearn.model_selection import GridSearchCV

def build_neural_network(optimizer):
    neural_network = Sequential()
    neural_network.add(Dense(input_dim = 11, units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    neural_network.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    neural_network.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    neural_network.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return neural_network

neural_network = KerasClassifier(build_fn = build_neural_network)

parameters = {'batch_size': [25,32], 'epochs': [100, 500], 'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = neural_network, param_grid = parameters, scoring = 'accuracy', cv = 10)
grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_